### ISSUE TITLE
UI doesn't show  "ETH or DAI" payment option at checkout  when running locally on windows

### ISSUE THREAD

**Issue by rahul-kothari** [esPass/pretix-eth-payment-plugin#147]
* Version: x.x.x
* Python: 3.6
* OS: win

### What was wrong?
Pretix UI doesn't show "ETH or DAI" payment option at checkout when running locally on windows.

On checking the log, there was 1 error found:
```
ERROR 2021-06-14 11:11:19,432 celery.app.trace trace Task pretix.presale.style.regenerate_css[92e8e620-c91e-4bc7-a3c1-7b35976e6352] raised unexpected: CompileError('Error: File to import not found or unreadable: main.scss.\n        on line 5:1 of stdin\n>> @import "main.scss";\n   ^\n')
Traceback (most recent call last):
  File "/mnt/c/Users/rahco/Desktop/Rahul/Freelance/pretix-eth-payment-plugin/venv/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/mnt/c/Users/rahco/Desktop/Rahul/Freelance/pretix-eth-payment-plugin/venv/lib/python3.8/site-packages/pretix/base/services/tasks.py", line 62, in __call__
    ret = super().__call__(*args, **kwargs)
  File "/mnt/c/Users/rahco/Desktop/Rahul/Freelance/pretix-eth-payment-plugin/venv/lib/python3.8/site-packages/pretix/base/services/tasks.py", line 108, in __call__
    ret = super().__call__(*args, **kwargs)
  File "/mnt/c/Users/rahco/Desktop/Rahul/Freelance/pretix-eth-payment-plugin/venv/lib/python3.8/site-packages/celery/app/task.py", line 393, in __call__
    return self.run(*args, **kwargs)
  File "/mnt/c/Users/rahco/Desktop/Rahul/Freelance/pretix-eth-payment-plugin/venv/lib/python3.8/site-packages/pretix/presale/style.py", line 139, in regenerate_css
    css, checksum = compile_scss(event)
  File "/mnt/c/Users/rahco/Desktop/Rahul/Freelance/pretix-eth-payment-plugin/venv/lib/python3.8/site-packages/pretix/presale/style.py", line 113, in compile_scss
    css = sass.compile(
  File "/mnt/c/Users/rahco/Desktop/Rahul/Freelance/pretix-eth-payment-plugin/venv/lib/python3.8/site-packages/sass.py", line 738, in compile
    raise CompileError(v)
sass.CompileError: Error: File to import not found or unreadable: main.scss.
        on line 5:1 of stdin
>> @import "main.scss";
```

### How can it be fixed?
Seems to be a bug in the pretix library.

**Comment by ligi** [comment]
wallets where not uploaded - solved by #153
