### ISSUE TITLE
Viewing pending orders in admin mode causes an error

### ISSUE THREAD

**Issue by jpitts** [esPass/pretix-eth-payment-plugin#18]
I am not sure if this relates to the Ethereum Plugin or if it is for pretix itself. I am able to view orders, but viewing pending orders from the Ethereum Plugin causes an error. This is from the pretix log at /var/pretix/data/logs/pretix.log:

```ERROR 2019-07-08 22:31:30,152 django.request log Internal Server Error: /control/event/devcon/5/orders/G0DDF/
Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/pretix/venv/lib/python3.7/site-packages/pretix/control/permissions.py", line 27, in wrapper
    return function(request, *args, **kw)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/var/pretix/venv/lib/python3.7/site-packages/pretix/control/views/orders.py", line 203, in get_context_data
    p.html_info = (p.payment_provider.payment_control_render(self.request, p) or "").strip()
  File "/var/pretix/venv/lib/python3.7/site-packages/pretix_eth/payment.py", line 213, in payment_control_render
    'coin': request.session['payment_ethereum_fm_currency']}
  File "/var/pretix/venv/lib/python3.7/site-packages/django/contrib/sessions/backends/base.py", line 54, in __getitem__
    return self._session[key]
KeyError: 'payment_ethereum_fm_currency'```

**Comment by ligi** [comment]
did not see this error anymore
